### ISSUE TITLE
Tests fail with setuptools 72.1.0

### ISSUE THREAD

**Issue by mweinelt** [scikit-build/scikit-build#1109]
Hi, we're seeing a number of tests fail in the same way after updating setuptools from 70.0 to 72.1.0 on skbuild 0.18.0.

This is the complete log of the test run: https://gist.github.com/mweinelt/78419fda7cfc28f7faec11de42e41bef

```
FAILED tests/test_cmakelists_not_in_top_level_dir.py::test_build - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_command_line.py::test_hide_listing[True-sdist] - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_command_line.py::test_hide_listing[True-bdist_wheel] - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_command_line.py::test_hide_listing[False-sdist] - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_command_line.py::test_hide_listing[False-bdist_wheel] - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_cython_flags.py::test_hello_cython_builds - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_filter_manifest.py::test_bdist_wheel_command - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_hello_cpp.py::test_hello_builds - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_hello_cpp.py::test_hello_clean[with-dry-run] - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_hello_cpp.py::test_hello_clean[without-dry-run] - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_hello_cpp.py::test_hello_cleans - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_hello_cython.py::test_hello_cython_builds - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_hello_cython.py::test_hello_cython_wheel - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_hello_pure.py::test_hello_pure_builds - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_hello_pure.py::test_hello_pure_wheel - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_hello_pure.py::test_hello_clean - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_include_exclude_data.py::test_include_exclude_data - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_include_exclude_data.py::test_include_exclude_data_with_base - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_issue284_build_ext_inplace.py::test_build_ext_inplace_command - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_issue335_support_cmake_source_dir.py::test_bdist_wheel_command - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_issue668_symbol_visibility.py::test_symbol_visibility[ON] - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_issue668_symbol_visibility.py::test_symbol_visibility[OFF] - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_manifest_in.py::test_manifest_in_wheel - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_skbuild.py::test_generator[Unix Makefiles-make] - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_skbuild_variable.py::test_skbuild_variable_sdist - AttributeError: 'dict' object has no attribute 'add'
FAILED tests/test_skbuild_variable.py::test_skbuild_variable_wheel - AttributeError: 'dict' object has no attribute 'add'
```

**Comment by henryiii** [comment]
Looks like a set is now a dict somewhere.

**Comment by henryiii** [comment]
This sounds like something we fixed... Ah, yes, it's https://github.com/scikit-build/scikit-build/pull/1103.

**Comment by mweinelt** [comment]
With that applied tests are looking good here. Thank you!
